stages:
  - test
  - build
  - container

image: debian:stable-slim

before_script:
  - apt-get update -qq && apt-get install -y -qq docker golang make

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make kube-health

container:
  stage: package
  script:
    - make container
