stages:
  - test
  - build
  - package

image: docker:latest

before_script:
  - apk update && apk add go make git

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make kube-health

container:
  stage: package
  script:
    - make container
