stages:
  - test
  - build
  - package
  - push

services:
  - docker:dind

variables:
  RELEASE: $CI_COMMIT_TAG
  REVISION: $CI_COMMIT_SHA

image: docker:latest

before_script:
  - apk update && apk add --no-cache --virtual .build-deps gcc libc-dev libgcc make git go

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make kube-health

package:
  stage: package
  script:
    - make container

push:
 stage: push
 script:
   - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
   - docker tag kube-health:latest "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
   - docker tag kube-health:latest "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
   - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
   - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
