stages:
  - test
  - build
  - package

image: docker:latest

before_script:
  - apk update && apk add --no-cache --virtual .build-deps gcc libc-dev libgcc make git go

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make kube-health

package:
  stage: package
  script:
    - make container
