---
apiVersion: v1
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-health
  namespace: kube-system
  labels:
    app: kube-health
spec:
  template:
    metadata:
      labels:
        app: kube-health
    spec:
      containers:
      - image: kube-health
        name: kube-health
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/kubehealth
      volumes:
        - name: config-volume
          configMap:
            name: kube-health
---
apiVersion: v1
kind: Service
metadata:
  name: kube-health
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - nodePort: 30880
    port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: kube-health
